### ISSUE TITLE
Request details

### ISSUE THREAD

**Issue by GalikAnnamaria** [levendula-rete2019/intellibus#2]
Az egy embertől jövő request (amivel tehát kvázi buszt "rendel"), pontosan miből áll? Ha jól értem, legalább ezek az adatok minimum kellenek:

1. Ki rendeli (hogy biztosan ott dolgozó rendelje, valamint gondolom ehhez bejelentkezés is kell azon az appon)
2. Hova menne
3. Ha előre lehet kérni a fuvart, mikor indulna
4. Honnan indulna
5. Hányan mennek

**Comment by bzp99** [comment]
1. Rendelni két úton lehessen:

a) A megállóknál (terminal) legyen valami hozzáférési pont, ahol tudsz kérvényezni egy fuvart.

b) A mobilodon az app segítségével

Mindkét esetben szükség van valamiféle autentikációra, hogy – mint mondottad vala – ne tudjon Pizzás Józsi Prampampulihelyről (tehát aki nem ott dolgozik) is buszt hívni, ha lusta gyalogolni. Erre talán ezen a szinten elég egy felhasználónév jelszó párost fenntartani.

2. A requestben megmondja az utas, hogy hova szeretne eljutni végül.

**Kérdés: Ezt változtathassa meg útközben?**

Nyilván, ha vészhelyzet van, le KELL szállnia, akkor azt megtehesse valahogy, de hogy ha a bedugott vasalós helyzet áll fenn, akkor is megengedjük?

---

A maradék háromhoz semmi

_(én ezt először úgy értelmeztem, hogy ez 5 kérdés, amit tisztázzunk, de azóta felfogtam, hogy csak meg szeretnéd vitatni, mi legyen benne...)_

**Comment by GalikAnnamaria** [comment]
**Válasz a kérdésre:**
Meg kéne engedni, intelligens buszról van szó, tudjon újratervezni, tudja azt a minimumot, amit egy normális busztól is elvárhatunk (ami az, hogy mindenki ott száll le/fel, ahol ezt a kérelmét IDŐBEN jelzi. A megálló előtt ne nyomathasson satuféket a busszal.).

Úgy lehetne a legjobban megfogalmazni, hogy a leszállási szándékát jelezhesse, de a busz dolga, hogy meg tud-e még állni biztonságosan, nyilván, visszatolatni nem fog.

**Comment by bzp99** [comment]
> **Válasz a kérdésre:**
> Meg kéne engedni, intelligens buszról van szó, tudjon újratervezni, tudja azt a minimumot, amit egy normális busztól is elvárhatunk (ami az, hogy mindenki ott száll le/fel, ahol ezt a kérelmét IDŐBEN jelzi. A megálló előtt ne nyomathasson satuféket a busszal.).

Rendben, ez tetszik. Tehát lehet csinálni (de nem ez az alap, azt várjuk, hogy mindeki előre jelezzen (hiszen különben nehéz rendesen utat tervezni)), de időben. Plusz nyilván ha kerülő, akkor kevesebb prioritást élvez az ő módosítása, mint az eddigi szépen kidolgozott útvonal.

**Comment by bzp99** [comment]
Mivel ezt már a Docs-ban realizálgatjuk, lezárom. Nyisd újra nyugodtan, ha indokoltnak látod.
