### ISSUE TITLE
Problems with buses

### ISSUE THREAD

**Issue by GalikAnnamaria** [levendula-rete2019/intellibus#3]
Mi minősül az alábbiaknak?

1. **Technical Problem**
   : Alkatrész meghibásodás.

2. **Non-critical failure:**
  : A busz nem okoz halálos balesetet, nem válik menthetetlenné az állapota, vissza tud gurulni az állomásra, tud utasokat szállítani biztonságosan, nem romlik el a funkciója (oda megy, ahova mennie kell), kinyílnak az ajtói/bezáródnak.

**Comment by bzp99** [comment]
Szerintem a halálos vagy akármilyen baleset itt nem releváns egyáltalán, az nem *failure*.

Az viszont igen, hogy a busz fele felrobban-e és mozdulni sem tud, kész, vagy tényleg hogy csak egy kerék kidurrant :smile_cat:

**Comment by bzp99** [comment]
Egyébként az értelmezéssel kapcsolatban még:

Egyetértünk, hogy **technical problem** lehet bármilyen meghibásodás, ami lehet egyébként **non-critical failure** is, de akár **critical ”** is? Szóval ezek kicsit részhalmazok.
